version: "3.9"

services:
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"   # Redis server
      - "8001:8001"   # RedisInsight GUI
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}   # ðŸ”‘ Set your password here
    volumes:
      - redis-stack-data:/data

  postgres:
    image: postgres:16
    container_name: local-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: e_shop_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  redis-stack-data:
  pgdata: